Repository EssentialsX/Essentials, pull requests merged in 2018-03, with the labels that each got.

#735 Extra permissions for /seen and /whois information
  Essentials/src/com/earth2me/essentials/commands/Commandseen.java
  Essentials/src/com/earth2me/essentials/commands/Commandwhois.java
  Essentials/src/plugin.yml
Labels: enhancement

#1867 Fixes #1866: Adds color formatting to /mail sendall
  Essentials/src/com/earth2me/essentials/commands/Commandmail.java
Labels: enhancement

#1901 Update messages_pl.properties
  Essentials/src/messages_pl.properties
Labels: enhancement

#1888 Update messages_nl.properties
  Essentials/src/messages_nl.properties
Labels: enhancement

#1796 Replace vanishedPlayers list with set
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/com/earth2me/essentials/IEssentials.java
  Essentials/src/com/earth2me/essentials/User.java
  Essentials/src/net/ess3/api/IEssentials.java
Labels: bug

#1804 cancel-afk-on-interact and cancel-afk-on-move are now separate settings
  Essentials/src/com/earth2me/essentials/EssentialsEntityListener.java
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/User.java
Labels: enhancement

#1882 Implement new versioning as per #1873
  Essentials/pom.xml
  Essentials/src/config.yml
  Essentials/src/items.csv
  Essentials/src/messages.properties
  Essentials/src/messages_cs.properties
  Essentials/src/messages_da.properties
  Essentials/src/messages_de.properties
  Essentials/src/messages_en.properties
  Essentials/src/messages_es.properties
  Essentials/src/messages_et.properties
  Essentials/src/messages_fi.properties
  Essentials/src/messages_fr.properties
  Essentials/src/messages_hu.properties
  Essentials/src/messages_it.properties
  Essentials/src/messages_ko.properties
  Essentials/src/messages_lt.properties
  Essentials/src/messages_nl.properties
  Essentials/src/messages_pl.properties
  Essentials/src/messages_pt.properties
  Essentials/src/messages_pt_BR.properties
  Essentials/src/messages_ro.properties
  Essentials/src/messages_ru.properties
  Essentials/src/messages_sv.properties
  Essentials/src/messages_tr.properties
  Essentials/src/messages_zh_HK.properties
  Essentials/src/messages_zh_TW.properties
  Essentials/src/plugin.yml
  EssentialsAntiBuild/pom.xml
  EssentialsAntiBuild/src/plugin.yml
  EssentialsChat/pom.xml
  EssentialsChat/src/plugin.yml
  EssentialsGeoIP/pom.xml
  EssentialsGeoIP/src/plugin.yml
  EssentialsProtect/pom.xml
  EssentialsProtect/src/plugin.yml
  EssentialsSpawn/pom.xml
  EssentialsSpawn/src/plugin.yml
  EssentialsXMPP/pom.xml
  EssentialsXMPP/src/plugin.yml
  pom.xml
Labels: enhancement, ready
