Repository EssentialsX/Essentials, pull requests merged in 2019-12, with the labels that each got.

#2800 Build with GitHub Actions
  .github/workflows/build.yml
  .travis.yml
  Essentials/pom.xml
  pom.xml
Labels: type: enhancement

#2811 Save materials in unlimited by name
  Essentials/src/com/earth2me/essentials/UserData.java
  Essentials/src/com/earth2me/essentials/commands/Commandunlimited.java
Labels: bug: confirmed

#2606 Attempt to parse loop command input as a UUID
  Essentials/src/com/earth2me/essentials/commands/EssentialsLoopCommand.java
  Essentials/src/com/earth2me/essentials/utils/StringUtil.java
Labels: type: enhancement

#2700 Improve scheduler methods to use Java 1.8 lambdas
  Essentials/src/com/earth2me/essentials/Backup.java
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
Labels: status: ready

#2908 Improvements for delkit
  Essentials/src/com/earth2me/essentials/commands/Commanddelkit.java
Labels: bug: confirmed, status: ready
