Repository EssentialsX/Essentials, pull requests merged in 2019-02, with the labels that each got.

#2430 Switch Vault dependency to VaultAPI
  Essentials/pom.xml
  Essentials/src/com/earth2me/essentials/register/payment/methods/VaultEco.java
Labels: type: enhancement

#2428 Fix creating and using kits on legacy versions
  Essentials/src/com/earth2me/essentials/items/AbstractItemDb.java
  Essentials/src/com/earth2me/essentials/items/LegacyItemDb.java
Labels: bug: confirmed

#2431 Check Protect/AntiBuild config materials against Material enum
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/utils/EnumUtil.java
Labels: bug: confirmed

#2409 Use PaperLib to load chunks and teleport players async
  Essentials/pom.xml
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/com/earth2me/essentials/Teleport.java
  Essentials/src/com/earth2me/essentials/TimedTeleport.java
  Essentials/src/com/earth2me/essentials/utils/LocationUtil.java
  Essentials/test/com/earth2me/essentials/FakeServer.java
  EssentialsSpawn/pom.xml
  EssentialsSpawn/src/com/earth2me/essentials/spawn/EssentialsSpawnPlayerListener.java
  pom.xml
Labels: type: enhancement

#2434 Relocate PaperLib in EssentialsXSpawn too
  EssentialsSpawn/pom.xml
Labels: bug: confirmed

#2435 Allow console to use essentials color codes when sending mail
  Essentials/src/com/earth2me/essentials/commands/Commandmail.java
Labels: type: enhancement

#2432 Economy API: Attempt to find users by UUID if username not present
  Essentials/src/com/earth2me/essentials/api/Economy.java
  Essentials/test/com/earth2me/essentials/FakeServer.java
Labels: bug: confirmed, help wanted
