Repository EssentialsX/Essentials, pull requests merged in 2019-04, with the labels that each got.

#2469 Add PlayerCommandSendEvent listener to hide commands in autocomplete
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
Labels: type: enhancement

#2472 Add new item database API
  Essentials/src/com/earth2me/essentials/api/IItemDb.java
  Essentials/src/com/earth2me/essentials/items/AbstractItemDb.java
  Essentials/src/com/earth2me/essentials/items/FlatItemDb.java
  Essentials/src/com/earth2me/essentials/items/LegacyItemDb.java
  Essentials/src/net/ess3/api/IItemDb.java
  Essentials/src/net/ess3/api/PluginKey.java
Labels: type: enhancement

#1949 [Feature] Add config optn. to disable jail free tp
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/User.java
  Essentials/src/config.yml
Labels: type: enhancement

#2158 Sort /near by nearest player.
  Essentials/src/com/earth2me/essentials/commands/Commandnear.java
Labels: type: enhancement

#2166 Use chat instead of dispatchCommand
  Essentials/src/com/earth2me/essentials/EssentialsEntityListener.java
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/com/earth2me/essentials/commands/Commandsudo.java
Labels: help wanted, type: enhancement

#2455 Fixes #94 - Player with same first letters conflict
  Essentials/src/com/earth2me/essentials/commands/EssentialsCommand.java
Labels: type: enhancement

#1953 Expand /exp command
  Essentials/src/com/earth2me/essentials/commands/Commandexp.java
Labels: type: enhancement

#2063 Fixed when the mail has already cleared
  Essentials/src/com/earth2me/essentials/commands/Commandmail.java
Labels: status: waiting on author, type: enhancement

#2486 Lets remove unusual strings
  Essentials/src/messages.properties
Labels: type: enhancement

#2494 fix geoip country returning "." if the user is joining from localhost
  Essentials/src/messages.properties
  EssentialsGeoIP/src/com/earth2me/essentials/geoip/EssentialsGeoIPPlayerListener.java
Labels: type: enhancement
