Repository EssentialsX/Essentials, pull requests merged in 2020-11, with the labels that each got.

#3753 Update to 1.16.4
  .github/PULL_REQUEST_TEMPLATE/bug-fix.md
  .github/PULL_REQUEST_TEMPLATE/new-feature.md
  .idea/checkstyle-idea.xml
  Essentials/src/com/earth2me/essentials/utils/VersionUtil.java
  README.md
  pom.xml
Labels: type: enhancement

#3762 Split backup command by space
  Essentials/src/com/earth2me/essentials/Backup.java
Labels: type: bugfix

#3703 Add option to prevent replying from vanished players
  Essentials/src/com/earth2me/essentials/Console.java
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/User.java
  Essentials/src/com/earth2me/essentials/commands/Commandr.java
  Essentials/src/com/earth2me/essentials/messaging/IMessageRecipient.java
  Essentials/src/com/earth2me/essentials/messaging/SimpleMessageRecipient.java
  Essentials/src/config.yml
Labels: hacktoberfest-accepted, type: enhancement

#3763 Use ray-tracing based target block for 1.13.2+
  Essentials/src/com/earth2me/essentials/IUser.java
  Essentials/src/com/earth2me/essentials/User.java
  Essentials/src/com/earth2me/essentials/commands/Commandbreak.java
  Essentials/src/com/earth2me/essentials/commands/Commandeditsign.java
  Essentials/src/com/earth2me/essentials/commands/Commandlightning.java
  Essentials/src/com/earth2me/essentials/signs/SignPlayerListener.java
Labels: type: bugfix, type: enhancement

#3715 Fix /clear <player> <item> not clearing offhand
  Essentials/src/com/earth2me/essentials/commands/Commandclearinventory.java
  Essentials/src/com/earth2me/essentials/craftbukkit/InventoryWorkaround.java
Labels: type: bugfix

#3775 Fix tab completion for /delhome
  Essentials/src/com/earth2me/essentials/commands/Commanddelhome.java
Labels: type: bugfix

#3776 Allow users to modify existing homes when over homes limit
  Essentials/src/com/earth2me/essentials/commands/Commandsethome.java
Labels: type: bugfix
