Repository EssentialsX/Essentials, pull requests merged in 2020-12, with the labels that each got.

#3778 Fix respawn anchor explosion protection
  EssentialsProtect/src/main/java/com/earth2me/essentials/protect/EssentialsProtectBlockListener_1_16_R1.java
Labels: type: bugfix

#3808 Move paperlib off snapshot
  Essentials/build.gradle
Labels: type: enhancement

#3700 Allow console name to be translated
  Essentials/src/main/java/com/earth2me/essentials/Console.java
  Essentials/src/main/java/com/earth2me/essentials/EssentialsUpgrade.java
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandban.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandbanip.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandhelpop.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandkick.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandmsg.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandtempban.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandtempbanip.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandtp.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandunban.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandunbanip.java
  Essentials/src/main/resources/messages.properties
  EssentialsSpawn/src/main/java/com/earth2me/essentials/spawn/Commandspawn.java
  EssentialsXMPP/src/main/java/com/earth2me/essentials/xmpp/Commandxmpp.java
Labels: type: enhancement

#3817 Fix incompatibility on TacoSpigot and derivatives
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
Labels: type: bugfix

#3820 Add /warpinfo command
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandwarpinfo.java
  Essentials/src/main/resources/messages.properties
  Essentials/src/main/resources/plugin.yml
Labels: type: enhancement

#3816 Fix command handler not finding dynamically registered commands
  Essentials/src/main/java/com/earth2me/essentials/AlternativeCommandsHandler.java
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
Labels: type: bugfix

#3829 Update FakeServer
  Essentials/src/test/java/com/earth2me/essentials/FakeServer.java
Labels: type: enhancement

#3831 Fix build script not working when git repo isn't cloned
  build.gradle
Labels: type: enhancement

#3848 Fix incorrect /me behaviour in local chat
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandme.java
Labels: bug: confirmed

#3789 Add restart note to respawn listener priority option
  Essentials/src/main/resources/config.yml
Labels: type: enhancement

#3853 Fix Improper Use of Event API
  Essentials/src/main/java/net/ess3/api/events/AfkStatusChangeEvent.java
  Essentials/src/main/java/net/ess3/api/events/FlyStatusChangeEvent.java
  Essentials/src/main/java/net/ess3/api/events/GodStatusChangeEvent.java
  Essentials/src/main/java/net/ess3/api/events/IgnoreStatusChangeEvent.java
  Essentials/src/main/java/net/ess3/api/events/JailStatusChangeEvent.java
  Essentials/src/main/java/net/ess3/api/events/MuteStatusChangeEvent.java
  Essentials/src/main/java/net/ess3/api/events/NickChangeEvent.java
  Essentials/src/main/java/net/ess3/api/events/SignBreakEvent.java
  Essentials/src/main/java/net/ess3/api/events/SignCreateEvent.java
  Essentials/src/main/java/net/ess3/api/events/SignEvent.java
  Essentials/src/main/java/net/ess3/api/events/SignInteractEvent.java
  Essentials/src/main/java/net/ess3/api/events/StateChangeEvent.java
  Essentials/src/main/java/net/ess3/api/events/VanishStatusChangeEvent.java
Labels: type: bugfix

#3856 Fix AlternativeCommandsHandler not detecting some aliases
  .idea/checkstyle-idea.xml
  Essentials/src/main/java/com/earth2me/essentials/AlternativeCommandsHandler.java
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandessentials.java
  gradle.properties
  providers/PaperProvider/build.gradle
Labels: type: bugfix

#3628 Rework Currency Symbol Parsing
  Essentials/src/main/java/com/earth2me/essentials/Kit.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/java/com/earth2me/essentials/utils/NumberUtil.java
Labels: type: enhancement
