Repository EssentialsX/Essentials, pull requests merged in 2020-04, with the labels that each got.

#3069 Add passenger dismounting for teleports
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/Teleport.java
  Essentials/src/config.yml
  Essentials/src/messages.properties
Labels: status: waiting on author, type: enhancement

#3120 Implemented Server Uptime Placeholder
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
Labels: type: enhancement

#3117 Added real name boolean option for the /list command
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/PlayerList.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/config.yml
Labels: type: enhancement

#3145 scripts: fix buildtools script under windows git bash
  scripts/buildtools.sh
Labels: type: enhancement

#2833 Add check for NPCs to /back listeners
  Essentials/src/com/earth2me/essentials/EssentialsEntityListener.java
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
Labels: type: enhancement

#3057 Change {PLAYER} to {USERNAME} in kits.yml comment
  Essentials/src/kits.yml
Labels: type: enhancement

#3149 Prevent tridents from being picked up
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/com/earth2me/essentials/commands/Commandfireball.java
Labels: bug: confirmed

#3151 Improve config.yml comments and structure
  Essentials/src/config.yml
Labels: type: enhancement

#2780 Allow toggling public broadcast of AFK messages
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/com/earth2me/essentials/IEssentials.java
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/User.java
  Essentials/src/com/earth2me/essentials/commands/Commandafk.java
  Essentials/src/config.yml
  Essentials/src/messages.properties
Labels: type: enhancement

#3101 Add /ecreative alias to /gamemode
  Essentials/src/plugin.yml
Labels: status: waiting on author, type: enhancement

#3173 Fix book formatting
  Essentials/src/book.txt
Labels: type: enhancement

#2546 Config option to toggle disabling flight / speed on world change
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/config.yml
Labels: type: enhancement

#3029 Add permissions defaults to plugin.yml for op-affecting commands
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/com/earth2me/essentials/commands/Commandhat.java
  Essentials/src/plugin.yml
  EssentialsAntiBuild/src/plugin.yml
Labels: type: enhancement

#3068 Improve MuteStatusChangeEvent
  Essentials/src/com/earth2me/essentials/User.java
  Essentials/src/com/earth2me/essentials/commands/Commandmute.java
  Essentials/src/net/ess3/api/events/MuteStatusChangeEvent.java
Labels: type: enhancement

#3066 Add config option to make currency symbol as a suffix
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Kit.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/utils/NumberUtil.java
  Essentials/src/config.yml
Labels: type: enhancement

#3206 Fix home tab completions
  Essentials/src/com/earth2me/essentials/commands/Commanddelhome.java
  Essentials/src/com/earth2me/essentials/commands/Commandhome.java
  Essentials/src/com/earth2me/essentials/commands/Commandsethome.java
Labels: bug: confirmed

#3210 Add protect option for disabling ender crystal explosions
  Essentials/src/config.yml
  EssentialsProtect/src/com/earth2me/essentials/protect/EssentialsProtectEntityListener.java
  EssentialsProtect/src/com/earth2me/essentials/protect/ProtectConfig.java
Labels: type: enhancement
