Repository EssentialsX/Essentials, pull requests merged in 2020-02, with the labels that each got.

#2994 Properly escape pipe character on item lore
  Essentials/src/com/earth2me/essentials/MetaItemStack.java
Labels: bug: confirmed

#2980 Explain how to add commands to kits
  Essentials/src/kits.yml
Labels: status: ready, type: enhancement

#3022 Fix CustomItemResolver causing a StackOverflowError
  Essentials/src/com/earth2me/essentials/items/CustomItemResolver.java
Labels: bug: confirmed

#3028 Clarify easter egg config description
  Essentials/src/config.yml
Labels: type: enhancement

#3026 Reduce permission check calls in PlayerCommandSendEvent
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
Labels: type: enhancement

#3027 Fix /fireball on 1.8.8
  Essentials/src/com/earth2me/essentials/commands/Commandfireball.java
Labels: bug: confirmed
