Repository EssentialsX/Essentials, pull requests merged in 2020-03, with the labels that each got.

#3064 User#payUser(User, BigDecimal, Cause) doesn't properly utilize Cause (Fixes #3062)
  Essentials/src/com/earth2me/essentials/User.java
Labels: type: enhancement

#2952 Adding Essentials speed info into whois
  Essentials/src/com/earth2me/essentials/commands/Commandwhois.java
  Essentials/src/messages.properties
Labels: status: ready, type: enhancement

#2754 Added in option to remove effects on heal
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/commands/Commandheal.java
  Essentials/src/config.yml
Labels: status: ready, type: enhancement

#2661 Add tab-completer for /spawnmob command
  Essentials/src/com/earth2me/essentials/commands/Commandspawnmob.java
Labels: status: ready, type: enhancement

#2755 Fixed double local logging
  EssentialsChat/src/com/earth2me/essentials/chat/EssentialsChatPlayerListenerNormal.java
Labels: bug: confirmed, status: ready

#2807 Implement max mute time feature
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/commands/Commandmute.java
  Essentials/src/config.yml
  Essentials/src/messages.properties
Labels: status: ready, type: enhancement

#2929 Add {PLAYER} placeholder with uppercase in kits
  Essentials/src/com/earth2me/essentials/Kit.java
Labels: status: ready, type: enhancement

#3107 Mention 1.15.2 in the README
  README.md
Labels: type: enhancement

#3048 Fix bed message on some older versions of MC
  Essentials/src/com/earth2me/essentials/utils/MaterialUtil.java
Labels: bug: confirmed

#2503 permission-based jail functions
  Essentials/src/com/earth2me/essentials/Jails.java
Labels: pull: next, status: ready, type: enhancement

#2505 implement command teleporting to a player's last known logout location
  Essentials/src/com/earth2me/essentials/commands/Commandtp.java
  Essentials/src/com/earth2me/essentials/commands/Commandtpoffline.java
  Essentials/src/com/earth2me/essentials/commands/EssentialsCommand.java
  Essentials/src/messages.properties
  Essentials/src/plugin.yml
Labels: type: enhancement

#2590 Add teleport warmup event to API
  Essentials/src/com/earth2me/essentials/Teleport.java
  Essentials/src/net/ess3/api/events/UserTeleportEvent.java
Labels: status: ready, type: enhancement

#2721 Implement message for #2640
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/messages.properties
Labels: status: waiting on author, type: enhancement

#2805 Add different translation keys for the "me" message
  Essentials/src/com/earth2me/essentials/messaging/SimpleMessageRecipient.java
  Essentials/src/messages.properties
  Essentials/src/messages_de.properties
Labels: status: ready, type: enhancement

#2820 Make drop-items-if-full work on Essentials kits
  Essentials/src/com/earth2me/essentials/Kit.java
  Essentials/src/com/earth2me/essentials/commands/Commandkit.java
  Essentials/src/com/earth2me/essentials/craftbukkit/InventoryWorkaround.java
  Essentials/src/messages.properties
Labels: status: ready, type: enhancement

#2914 Fix NPE when the user is null in the hidden players
  Essentials/src/com/earth2me/essentials/PlayerList.java
  Essentials/src/com/earth2me/essentials/commands/Commandlightning.java
Labels: status: ready, type: enhancement

#3049 Near exclude permission
  Essentials/src/com/earth2me/essentials/commands/Commandnear.java
  Essentials/src/plugin.yml
Labels: type: enhancement

#3051 Fix tab completion for Exp command
  Essentials/src/com/earth2me/essentials/commands/Commandexp.java
Labels: bug: confirmed

#3052 Fix zh-CN GeoIP locale issue
  EssentialsGeoIP/src/com/earth2me/essentials/geoip/EssentialsGeoIPPlayerListener.java
Labels: bug: confirmed

#3063 Implement better AfkStatusChangeEvent
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/com/earth2me/essentials/IUser.java
  Essentials/src/com/earth2me/essentials/User.java
  Essentials/src/com/earth2me/essentials/commands/Commandafk.java
  Essentials/src/net/ess3/api/events/AfkStatusChangeEvent.java
Labels: type: enhancement

#3106 Make MockBukkit compatible #3105
  Essentials/src/com/earth2me/essentials/Essentials.java
Labels: type: enhancement
