Repository EssentialsX/Essentials, pull requests merged in 2020-10, with the labels that each got.

#3695 Bump Paperlib version
  Essentials/pom.xml
Labels: bug: confirmed, bug: upstream

#3699 Remove sign color codes from trade.log
  Essentials/src/com/earth2me/essentials/signs/EssentialsSign.java
  Essentials/src/com/earth2me/essentials/signs/SignTrade.java
Labels: hacktoberfest-accepted, type: enhancement

#3693 Use username instead of nickname in console /sell messages
  Essentials/src/com/earth2me/essentials/commands/Commandsell.java
Labels: hacktoberfest-accepted, type: enhancement

#3678 Update old EssentialsX URLs in issue templates
  .github/ISSUE_TEMPLATE/help.md
  .github/ISSUE_TEMPLATE/request-a-feature.md
Labels: type: enhancement

#3704 Add more inventory commands
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/com/earth2me/essentials/IEssentials.java
  Essentials/src/com/earth2me/essentials/commands/Commandanvil.java
  Essentials/src/com/earth2me/essentials/commands/Commandcartographytable.java
  Essentials/src/com/earth2me/essentials/commands/Commandgrindstone.java
  Essentials/src/com/earth2me/essentials/commands/Commandloom.java
  Essentials/src/com/earth2me/essentials/commands/Commandsmithingtable.java
  Essentials/src/com/earth2me/essentials/commands/Commandstonecutter.java
  Essentials/src/messages.properties
  Essentials/src/plugin.yml
  providers/BaseProviders/src/net/ess3/provider/ContainerProvider.java
  providers/PaperProvider/pom.xml
  providers/PaperProvider/src/net/ess3/provider/providers/PaperContainerProvider.java
Labels: hacktoberfest-accepted, type: enhancement

#3713 Tab-complete plugin names for `/help`
  Essentials/src/com/earth2me/essentials/commands/Commandhelp.java
  Essentials/src/com/earth2me/essentials/commands/EssentialsCommand.java
Labels: type: enhancement

#3716 Remove acacia & birch tree type arguments from tree command
  Essentials/src/com/earth2me/essentials/commands/Commandtree.java
Labels: type: enhancement

#3675 Make HelpInput use the known command map
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/com/earth2me/essentials/IEssentials.java
  Essentials/src/com/earth2me/essentials/commands/EssentialsCommand.java
  Essentials/src/com/earth2me/essentials/textreader/HelpInput.java
  providers/BaseProviders/src/net/ess3/provider/KnownCommandsProvider.java
  providers/NMSReflectionProvider/src/net/ess3/nms/refl/providers/ReflKnownCommandsProvider.java
  providers/PaperProvider/src/net/ess3/provider/providers/PaperKnownCommandsProvider.java
Labels: type: enhancement

#3739 Move some tab complete messages to debug mode only
  Essentials/src/com/earth2me/essentials/commands/EssentialsCommand.java
Labels: type: bugfix

#3711 Add new PR templates and revamp issue templates
  .github/ISSUE_TEMPLATE/help.md
  .github/ISSUE_TEMPLATE/report-a-bug.md
  .github/ISSUE_TEMPLATE/request-a-feature.md
  .github/PULL_REQUEST_TEMPLATE/bug-fix.md
  .github/PULL_REQUEST_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE/new-feature.md
  CONTRIBUTING.md
  README.md
Labels: type: enhancement
