Repository EssentialsX/Essentials, pull requests merged in 2020-05, with the labels that each got.

#3218 Don't show hidden players in /balance unless exact name entered
  Essentials/src/com/earth2me/essentials/commands/Commandbalance.java
  Essentials/src/com/earth2me/essentials/commands/EssentialsCommand.java
Labels: type: enhancement

#3085 Add UUID and User based economy methods
  Essentials/src/com/earth2me/essentials/api/Economy.java
  Essentials/src/com/earth2me/essentials/api/UserDoesNotExistException.java
  Essentials/src/messages.properties
Labels: type: enhancement

#3209 Convert ignore list storage to UUID-based
  Essentials/src/com/earth2me/essentials/EssentialsUpgrade.java
  Essentials/src/com/earth2me/essentials/UserData.java
  Essentials/src/com/earth2me/essentials/commands/Commandignore.java
Labels: type: enhancement

#3070 Add default enchantment level for enchant sign
  Essentials/src/com/earth2me/essentials/signs/SignEnchant.java
Labels: type: enhancement

#3247 Add a more helpful error message for xmpp module
  Essentials/src/messages.properties
  EssentialsXMPP/src/com/earth2me/essentials/xmpp/XMPPManager.java
Labels: type: enhancement

#3197 Add KitClaimEvent
  Essentials/src/com/earth2me/essentials/Kit.java
  Essentials/src/net/ess3/api/events/KitClaimEvent.java
Labels: type: enhancement

#3157 Save player logout times on shutdown
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/com/earth2me/essentials/craftbukkit/ServerState.java
Labels: type: enhancement

#3253 Fix invalid charge error when using suffix currency on signs
  Essentials/src/com/earth2me/essentials/Kit.java
  Essentials/src/com/earth2me/essentials/signs/EssentialsSign.java
  Essentials/src/com/earth2me/essentials/signs/SignTrade.java
  Essentials/src/com/earth2me/essentials/utils/NumberUtil.java
Labels: bug: confirmed

#3258 Improve backup functionality
  Essentials/src/com/earth2me/essentials/Backup.java
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/config.yml
  Essentials/src/messages.properties
Labels: bug: confirmed

#3205 Implement rest command
  Essentials/src/com/earth2me/essentials/commands/Commandrest.java
  Essentials/src/messages.properties
  Essentials/src/plugin.yml
Labels: type: enhancement

#2826 Implement permission node to extinguish other players
  Essentials/src/com/earth2me/essentials/commands/Commandext.java
Labels: status: waiting on author, type: enhancement

#3268 Use world's sea level for depth command
  Essentials/src/com/earth2me/essentials/commands/Commanddepth.java
Labels: type: enhancement

#3265 Add offhand slot to invsee equip
  Essentials/src/com/earth2me/essentials/commands/Commandinvsee.java
Labels: type: enhancement

#3264 Allow 1 character names in msg command
  Essentials/src/com/earth2me/essentials/commands/Commandmsg.java
Labels: type: enhancement

#3080 Added a command to /eco that allows users to take percentages from pl…
  Essentials/src/com/earth2me/essentials/commands/Commandeco.java
Labels: status: waiting on author, type: enhancement

#3260 implement PrivateMessagePreSendEvent
  Essentials/src/com/earth2me/essentials/messaging/IMessageRecipient.java
  Essentials/src/com/earth2me/essentials/messaging/SimpleMessageRecipient.java
  Essentials/src/net/ess3/api/events/PrivateMessagePreSendEvent.java
Labels: type: enhancement

#3276 Remove 1.8 NMS spawner providers
  Essentials/src/com/earth2me/essentials/Essentials.java
  nms/1_8_R1Provider/.gitignore
  nms/1_8_R1Provider/pom.xml
  nms/1_8_R1Provider/src/net/ess3/nms/v1_8_R1/v1_8_R1SpawnerProvider.java
  nms/1_8_R2Provider/.gitignore
  nms/1_8_R2Provider/pom.xml
  nms/1_8_R2Provider/src/net/ess3/nms/v1_8_R2/v1_8_R2SpawnerProvider.java
  pom.xml
Labels: type: enhancement

#3271 Fix improper target block handing in /tree & /bigtree
  Essentials/src/com/earth2me/essentials/commands/Commandbigtree.java
  Essentials/src/com/earth2me/essentials/commands/Commandtree.java
Labels: type: enhancement

#3288 Ignore CloudNet v3 SLPE
  Essentials/src/com/earth2me/essentials/EssentialsServerListener.java
Labels: type: enhancement

#3263 Fix clearing specific items in clearinventory
  Essentials/src/com/earth2me/essentials/commands/Commandclearinventory.java
Labels: bug: confirmed

#3334 Update config.yml custom join/quit message comments
  Essentials/src/config.yml
Labels: type: enhancement

#3335 Add missing methods to Commandexp
  Essentials/src/com/earth2me/essentials/commands/Commandexp.java
Labels: bug: confirmed

#3207 send-info-after-death
  Essentials/src/com/earth2me/essentials/EssentialsEntityListener.java
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/config.yml
  Essentials/src/messages.properties
Labels: type: enhancement

#3273 Add config option to block /pay from ignored users
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/commands/Commandpay.java
  Essentials/src/config.yml
Labels: type: enhancement

#3291 Add tempbanip command
  Essentials/src/com/earth2me/essentials/commands/Commandtempbanip.java
  Essentials/src/messages.properties
  Essentials/src/plugin.yml
Labels: type: enhancement

#3299 Block removing hats with curse of binding
  Essentials/src/com/earth2me/essentials/commands/Commandhat.java
  Essentials/src/messages.properties
Labels: type: enhancement

#3270 Protect Armor Stands + Item Frames
  EssentialsAntiBuild/src/com/earth2me/essentials/antibuild/EssentialsAntiBuildListener.java
Labels: type: enhancement

#3340 Fix bug with eco reset requiring 3 arguments when it shouldn't
  Essentials/src/com/earth2me/essentials/commands/Commandeco.java
Labels: bug: confirmed

#3341 Player should not be able to send empty shout/question messages
  EssentialsChat/src/com/earth2me/essentials/chat/EssentialsChatPlayer.java
Labels: bug: confirmed

#3279 Clean up providers a bit
  nms/FlattenedProvider/src/net/ess3/nms/flattened/FlatSpawnEggProvider.java
  nms/LegacyProvider/src/net/ess3/nms/legacy/LegacyPotionMetaProvider.java
  nms/LegacyProvider/src/net/ess3/nms/legacy/LegacySpawnEggProvider.java
  nms/LegacyProvider/src/net/ess3/nms/legacy/LegacySpawnerProvider.java
  nms/NMSProvider/src/net/ess3/nms/SpawnEggProvider.java
  nms/NMSProvider/src/net/ess3/nms/SpawnerProvider.java
  nms/NMSProvider/src/net/ess3/providers/Provider.java
  nms/NMSProvider/src/net/ess3/providers/ProviderFactory.java
  nms/ReflectionProvider/src/net/ess3/nms/refl/ReflSpawnEggProvider.java
  nms/ReflectionProvider/src/net/ess3/nms/refl/ReflUtil.java
  nms/ReflectionProvider/src/net/ess3/nms/refl/SpawnEggRefl.java
  nms/UpdatedMetaProvider/src/net/ess3/nms/updatedmeta/BasePotionDataProvider.java
  nms/UpdatedMetaProvider/src/net/ess3/nms/updatedmeta/BlockMetaSpawnerProvider.java
Labels: type: enhancement

#3292 Display date diff correctly
  Essentials/src/com/earth2me/essentials/utils/DateUtil.java
Labels: type: enhancement
