Repository EssentialsX/Essentials, pull requests merged in 2020-06, with the labels that each got.

#3320 Add support for permission contexts
  Essentials/pom.xml
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/com/earth2me/essentials/EssentialsPluginListener.java
  Essentials/src/com/earth2me/essentials/perm/IPermissionsHandler.java
  Essentials/src/com/earth2me/essentials/perm/PermissionsHandler.java
  Essentials/src/com/earth2me/essentials/perm/impl/LuckPermsHandler.java
  Essentials/src/com/earth2me/essentials/perm/impl/SuperpermsHandler.java
  Essentials/src/plugin.yml
Labels: type: enhancement

#3269 Add option to change disposal title via sign
  Essentials/src/com/earth2me/essentials/signs/SignDisposal.java
Labels: type: enhancement

#3358 Add UTF8 support for .properties files
  Essentials/src/com/earth2me/essentials/I18n.java
  pom.xml
Labels: type: enhancement

#3366 Fix inconsistent coloring in messages
  Essentials/src/messages.properties
Labels: type: enhancement

#3361 Deny teleport requests to players lacking permission to accept
  Essentials/src/com/earth2me/essentials/commands/Commandtpa.java
  Essentials/src/messages.properties
Labels: type: enhancement

#3314 Add config option to control selling names items with /sell
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/commands/Commandsell.java
  Essentials/src/config.yml
  Essentials/src/messages.properties
Labels: type: enhancement

#3307 Add serialize method to ItemResolvers for custom serialization
  Essentials/src/com/earth2me/essentials/api/IItemDb.java
  Essentials/src/com/earth2me/essentials/items/AbstractItemDb.java
  Essentials/src/com/earth2me/essentials/items/FlatItemDb.java
  Essentials/src/com/earth2me/essentials/items/LegacyItemDb.java
  Essentials/src/net/ess3/api/IItemDb.java
Labels: type: enhancement

#2504 Add settings to protect items from explosions
  Essentials/src/config.yml
  EssentialsProtect/src/com/earth2me/essentials/protect/EssentialsProtectBlockListener.java
  EssentialsProtect/src/com/earth2me/essentials/protect/ProtectConfig.java
Labels: status: waiting on author, type: enhancement

#3328 Add option to remove vanishing items from keepinv users
  Essentials/src/com/earth2me/essentials/EssentialsEntityListener.java
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/config.yml
Labels: type: enhancement

#3284 Add support for translating command description and usage
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/messages.properties
Labels: type: enhancement

#3391 Fix a messages.properties message
  Essentials/src/messages.properties
Labels: type: enhancement

#3412 Fix spawner provider on 1.16
  providers/BaseProviders/src/net/ess3/provider/SpawnerProvider.java
Labels: bug: confirmed

#3395 Merge pop4959/raiders into mc/1.16
  Essentials/src/com/earth2me/essentials/Mob.java
  Essentials/src/com/earth2me/essentials/MobCompat.java
  Essentials/src/com/earth2me/essentials/MobData.java
  Essentials/src/com/earth2me/essentials/SpawnMob.java
  Essentials/src/com/earth2me/essentials/utils/VersionUtil.java
Labels: type: enhancement

#3408 Update to 1.16.1
  Essentials/pom.xml
  Essentials/src/com/earth2me/essentials/AsyncTeleport.java
  Essentials/src/com/earth2me/essentials/Enchantments.java
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Mob.java
  Essentials/src/com/earth2me/essentials/MobCompat.java
  Essentials/src/com/earth2me/essentials/MobData.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/SpawnMob.java
  Essentials/src/com/earth2me/essentials/User.java
  Essentials/src/com/earth2me/essentials/commands/Commandspawnmob.java
  Essentials/src/com/earth2me/essentials/craftbukkit/FakeWorld.java
  Essentials/src/com/earth2me/essentials/utils/FormatUtil.java
  Essentials/src/com/earth2me/essentials/utils/VersionUtil.java
  Essentials/src/config.yml
  Essentials/test/com/earth2me/essentials/FakeServer.java
  EssentialsSpawn/pom.xml
  EssentialsSpawn/src/com/earth2me/essentials/spawn/EssentialsSpawnPlayerListener.java
  README.md
  pom.xml
  providers/1_8Provider/pom.xml
  providers/1_8Provider/src/com/earth2me/essentials/OfflinePlayer.java
Labels: type: enhancement

#3422 Fix RGB support in prefixes/suffixes
  Essentials/src/com/earth2me/essentials/User.java
Labels: bug: confirmed

#3427 Fix paperlib relocation pattern for EssentialsXSpawn
  EssentialsSpawn/pom.xml
Labels: bug: confirmed

#3433 Fix some reported bugs regarding teleportation.
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/commands/Commandhome.java
  Essentials/src/com/earth2me/essentials/utils/LocationUtil.java
  Essentials/src/config.yml
Labels: bug: confirmed
