Repository EssentialsX/Essentials, pull requests merged in 2020-07, with the labels that each got.

#3434 Add command + money queues to process after items in kits
  Essentials/src/com/earth2me/essentials/Kit.java
Labels: bug: confirmed

#3415 EditSign Command
  Essentials/src/com/earth2me/essentials/commands/Commandeditsign.java
  Essentials/src/messages.properties
  Essentials/src/plugin.yml
Labels: type: enhancement

#3338 Confirm home replacement when overwriting existing homes
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/User.java
  Essentials/src/com/earth2me/essentials/UserData.java
  Essentials/src/com/earth2me/essentials/commands/Commandsethome.java
  Essentials/src/config.yml
  Essentials/src/messages.properties
Labels: type: enhancement

#3388 Improve suicide and kill commands
  Essentials/src/com/earth2me/essentials/commands/Commandkill.java
  Essentials/src/com/earth2me/essentials/commands/Commandsuicide.java
Labels: type: enhancement

#3389 Ignore NPCs in EntityCombustByEntityEvent
  Essentials/src/com/earth2me/essentials/EssentialsEntityListener.java
Labels: type: enhancement

#3396 Match kit name in delkit
  Essentials/src/com/earth2me/essentials/Kits.java
  Essentials/src/com/earth2me/essentials/commands/Commanddelkit.java
Labels: type: enhancement

#3404 Fix recipe command on Paper
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/com/earth2me/essentials/commands/Commandrecipe.java
  providers/BaseProviders/src/net/ess3/provider/ProviderListener.java
  providers/PaperProvider/src/net/ess3/provider/providers/PaperRecipeBookListener.java
Labels: type: enhancement

#3444 Fix further AME(s) in /home
  Essentials/src/com/earth2me/essentials/commands/Commandhome.java
Labels: bug: confirmed

#3445 Add hidden config to stop throwing errors for passengers
  Essentials/src/com/earth2me/essentials/AsyncTeleport.java
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
Labels: type: enhancement

#3451 Update bStats version + add new graphs
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/com/earth2me/essentials/IEssentials.java
  Essentials/src/com/earth2me/essentials/metrics/Metrics.java
  Essentials/src/com/earth2me/essentials/metrics/MetricsWrapper.java
  Essentials/src/com/earth2me/essentials/perm/IPermissionsHandler.java
  Essentials/src/com/earth2me/essentials/perm/PermissionsHandler.java
  Essentials/src/com/earth2me/essentials/perm/impl/AbstractVaultHandler.java
  Essentials/src/com/earth2me/essentials/perm/impl/ConfigPermissionsHandler.java
  Essentials/src/com/earth2me/essentials/perm/impl/SuperpermsHandler.java
  Essentials/src/com/earth2me/essentials/register/payment/Method.java
  EssentialsAntiBuild/src/com/earth2me/essentials/antibuild/EssentialsAntiBuild.java
  EssentialsChat/src/com/earth2me/essentials/chat/EssentialsChat.java
  EssentialsGeoIP/src/com/earth2me/essentials/geoip/EssentialsGeoIP.java
  EssentialsProtect/src/com/earth2me/essentials/protect/EssentialsProtect.java
  EssentialsSpawn/src/com/earth2me/essentials/spawn/EssentialsSpawn.java
  EssentialsXMPP/src/com/earth2me/essentials/xmpp/EssentialsXMPP.java
Labels: type: enhancement

#3432 Add PrivateMessageSentEvent and fix PrivateMessagePreSendEvent
  Essentials/src/com/earth2me/essentials/messaging/SimpleMessageRecipient.java
  Essentials/src/net/ess3/api/events/PrivateMessageSentEvent.java
Labels: type: enhancement, type: problem

#3453 Allow preventing bed and respawn anchor explosions in Protect
  Essentials/src/config.yml
  EssentialsProtect/src/com/earth2me/essentials/protect/EssentialsProtect.java
  EssentialsProtect/src/com/earth2me/essentials/protect/EssentialsProtectBlockListener.java
  EssentialsProtect/src/com/earth2me/essentials/protect/EssentialsProtectBlockListener_1_16_R1.java
  EssentialsProtect/src/com/earth2me/essentials/protect/EssentialsProtectEntityListener_1_13_2_R1.java
  EssentialsProtect/src/com/earth2me/essentials/protect/ProtectConfig.java
Labels: type: enhancement

#3419 Correctly handle explicitly denied permissions for users without a permissions plugin
  Essentials/src/com/earth2me/essentials/perm/impl/SuperpermsHandler.java
Labels: type: enhancement

#3331 Add itemlore command
  Essentials/src/com/earth2me/essentials/commands/Commanditemlore.java
  Essentials/src/messages.properties
  Essentials/src/plugin.yml
Labels: type: enhancement

#3329 Add mute expiry time in mute messages
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/com/earth2me/essentials/commands/Commandafk.java
  Essentials/src/com/earth2me/essentials/commands/Commandmail.java
  Essentials/src/com/earth2me/essentials/commands/Commandme.java
  Essentials/src/com/earth2me/essentials/commands/Commandmsg.java
  Essentials/src/com/earth2me/essentials/commands/Commandr.java
  Essentials/src/messages.properties
Labels: type: enhancement

#3418 Implement random teleport command
  Essentials/src/com/earth2me/essentials/Essentials.java
  Essentials/src/com/earth2me/essentials/IEssentials.java
  Essentials/src/com/earth2me/essentials/RandomTeleport.java
  Essentials/src/com/earth2me/essentials/commands/Commandsettpr.java
  Essentials/src/com/earth2me/essentials/commands/Commandtpr.java
  Essentials/src/messages.properties
  Essentials/src/net/ess3/api/events/UserRandomTeleportEvent.java
  Essentials/src/plugin.yml
  Essentials/src/tpr.yml
Labels: type: enhancement

#3302 Allow for specifying amount to increase itemstack in /more
  Essentials/src/com/earth2me/essentials/commands/Commandmore.java
  Essentials/src/com/earth2me/essentials/utils/NumberUtil.java
  Essentials/src/messages.properties
  Essentials/src/plugin.yml
Labels: type: enhancement

#3464 Add config option to hide join/quit messages above X players
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/config.yml
Labels: type: enhancement

#3466 Choose better elevation for random nether teleport
  Essentials/src/com/earth2me/essentials/RandomTeleport.java
Labels: type: enhancement

#3192 Replace UserTeleportEvent with more sane events
  Essentials/src/com/earth2me/essentials/AsyncTeleport.java
  Essentials/src/com/earth2me/essentials/Teleport.java
  Essentials/src/net/ess3/api/events/UserTeleportEvent.java
  Essentials/src/net/ess3/api/events/teleport/PreTeleportEvent.java
  Essentials/src/net/ess3/api/events/teleport/TeleportEvent.java
  Essentials/src/net/ess3/api/events/teleport/TeleportWarmupEvent.java
Labels: type: enhancement

#3403 Add UserTeleportHomeEvent
  Essentials/src/com/earth2me/essentials/commands/Commandhome.java
  Essentials/src/net/ess3/api/events/UserTeleportHomeEvent.java
Labels: type: enhancement

#3473 exclude EssX commands from non-core modules as well
  Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
Labels: type: enhancement

#3476 Add jail contexts
  Essentials/src/com/earth2me/essentials/perm/PermissionsHandler.java
Labels: type: enhancement

#3478 Deny tpahere requests to players without permission to accept
  Essentials/src/com/earth2me/essentials/commands/Commandtpahere.java
Labels: type: enhancement

#3477 Fix issue with /remove skeletonhorse
  Essentials/src/com/earth2me/essentials/commands/Commandremove.java
Labels: type: enhancement

#3488 Typo, should be "match" not "maths".
  Essentials/src/com/earth2me/essentials/utils/EnumUtil.java
Labels: type: enhancement

#3496 Disable random tp pre-cache by default
  Essentials/src/com/earth2me/essentials/RandomTeleport.java
Labels: type: enhancement

#3487 Update MaterialUtil with new sign types
  Essentials/src/com/earth2me/essentials/utils/MaterialUtil.java
Labels: type: enhancement

#3480 Fixed how the random teleporter picks a location.
  Essentials/src/com/earth2me/essentials/RandomTeleport.java
Labels: type: enhancement

#3498 Add config option to respawn at respawn anchors
  Essentials/src/com/earth2me/essentials/ISettings.java
  Essentials/src/com/earth2me/essentials/Settings.java
  Essentials/src/config.yml
  EssentialsSpawn/src/com/earth2me/essentials/spawn/EssentialsSpawnPlayerListener.java
Labels: type: enhancement

#3522 Properly handle jail respawn in togglejail (Fixes #3520)
  Essentials/src/com/earth2me/essentials/commands/Commandtogglejail.java
Labels: bug: confirmed

#3497 Add sign text tab completion in editsign command
  Essentials/src/com/earth2me/essentials/commands/Commandeditsign.java
  Essentials/src/com/earth2me/essentials/utils/FormatUtil.java
  Essentials/test/com/earth2me/essentials/utils/FormatUtilTest.java
Labels: type: enhancement
