Repository EssentialsX/Essentials, pull requests merged in 2021-03, with the labels that each got.

#4025 Fix failing gradle build
  build.gradle
Labels: type: bugfix

#3855 Add update checker
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/main/java/com/earth2me/essentials/IEssentials.java
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandessentials.java
  Essentials/src/main/java/com/earth2me/essentials/metrics/MetricsWrapper.java
  Essentials/src/main/java/com/earth2me/essentials/updatecheck/UpdateChecker.java
  Essentials/src/main/resources/config.yml
  Essentials/src/main/resources/messages.properties
  Essentials/src/main/resources/release
  build.gradle
Labels: type: enhancement

#4031 Add netherite related items to spawnmob
  Essentials/src/main/java/com/earth2me/essentials/MobData.java
  Essentials/src/main/java/com/earth2me/essentials/SpawnMob.java
Labels: type: bugfix

#3968 Delay GeoIP join task to ensure display name is set
  Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/main/java/net/essentialsx/api/v2/events/AsyncUserDataLoadEvent.java
  EssentialsGeoIP/src/main/java/com/earth2me/essentials/geoip/EssentialsGeoIPPlayerListener.java
Labels: type: bugfix

#4032 Fix list command exposing groups with vanished players
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandlist.java
Labels: type: bugfix

#4039 Improve update checker startup message logging
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
Labels: type: enhancement

#4043 Update FakeWorld
  Essentials/src/main/java/com/earth2me/essentials/EssentialsUpgrade.java
  Essentials/src/main/java/com/earth2me/essentials/craftbukkit/FakeWorld.java
  Essentials/src/test/java/com/earth2me/essentials/FakeServer.java
  providers/1_8Provider/src/main/java/com/earth2me/essentials/FakeWorld.java
Labels: type: enhancement

#4049 Change createkit to use paste.gg
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandcreatekit.java
Labels: type: enhancement

#3987 Improve currency validation in signs
  Essentials/src/main/java/com/earth2me/essentials/signs/EssentialsSign.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignTrade.java
Labels: type: bugfix

#4069 Fix update check on 3+ digit build numbers
  Essentials/src/main/java/com/earth2me/essentials/updatecheck/UpdateChecker.java
Labels: type: bugfix

#4066 Fix delayed futures never being completed correctly
  Essentials/src/main/java/com/earth2me/essentials/AsyncTeleport.java
  Essentials/src/main/java/com/earth2me/essentials/AsyncTimedTeleport.java
Labels: type: bugfix

#4071 Add missing respawn-at-home-bed config option
  Essentials/src/main/resources/config.yml
Labels: type: problem

#4040 Implement discord interaction changes
  EssentialsDiscord/README.md
  EssentialsDiscord/src/main/java/net/essentialsx/discord/DiscordSettings.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/interactions/InteractionController.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/interactions/command/InteractionCommand.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/interactions/command/InteractionEvent.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/util/DiscordUtil.java
  EssentialsDiscord/src/main/resources/config.yml
Labels: type: enhancement

#4098 Add some extra keywords
  Essentials/src/main/java/com/earth2me/essentials/IUser.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/com/earth2me/essentials/textreader/KeywordReplacer.java
  Essentials/src/main/resources/config.yml
  Essentials/src/main/resources/info.txt
  EssentialsChat/src/main/java/com/earth2me/essentials/chat/EssentialsChatPlayerListenerLowest.java
Labels: type: enhancement
