Repository EssentialsX/Essentials, pull requests merged in 2021-01, with the labels that each got.

#3858 Fix behaviour of /list when showing real names
  Essentials/src/main/java/com/earth2me/essentials/PlayerList.java
Labels: bug: confirmed

#3863 Separate option to cancel afk on chat from interact
  Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/net/ess3/api/events/AfkStatusChangeEvent.java
  Essentials/src/main/resources/config.yml
Labels: type: enhancement

#3802 Add option to disable players respawning at beds
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  EssentialsSpawn/src/main/java/com/earth2me/essentials/spawn/EssentialsSpawnPlayerListener.java
Labels: type: enhancement

#3696 Fix warp messages sending incorrectly with teleport delays
  Essentials/src/main/java/com/earth2me/essentials/AsyncTeleport.java
Labels: type: enhancement

#3649 Add TransactionEvent for successful transactions
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/net/essentialsx/api/v2/events/TransactionEvent.java
Labels: type: enhancement

#3669 Add API to register enchantment names/aliases
  Essentials/src/main/java/com/earth2me/essentials/Enchantments.java
Labels: status: needs manual rebase, type: enhancement

#3636 Don't lowercase item names in IItemDb#get(String, int)
  Essentials/src/main/java/com/earth2me/essentials/api/IItemDb.java
Labels: status: needs manual rebase, type: enhancement

#3490 Add UserKickEvent
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandkick.java
  Essentials/src/main/java/net/essentialsx/api/v2/events/UserKickEvent.java
Labels: status: needs manual rebase, type: enhancement

#3721 Add ending user balance as a final field in trade.log
  Essentials/src/main/java/com/earth2me/essentials/Trade.java
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/com/earth2me/essentials/api/Economy.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandpay.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandsell.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignBuy.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignEnchant.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignFree.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignGameMode.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignHeal.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignInfo.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignKit.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignRepair.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignSell.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignSpawnmob.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignTime.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignTrade.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignWarp.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignWeather.java
Labels: type: enhancement

#3893 Allow users to middle click in armor invsee
  Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java
Labels: type: enhancement

#3691 Fix AbstractItemDb#getMatching improper block filtering
  Essentials/src/main/java/com/earth2me/essentials/items/AbstractItemDb.java
Labels: bug: confirmed, status: needs manual rebase, status: not enough info

#3895 Block removing hats with curse of binding using direct-hat
  Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java
Labels: type: bugfix

#3875 Add WarpModifyEvent
  Essentials/src/main/java/com/earth2me/essentials/commands/Commanddelwarp.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandsetwarp.java
  Essentials/src/main/java/net/essentialsx/api/v2/events/WarpModifyEvent.java
Labels: type: api, type: enhancement

#3625 Allow paying offline users via /pay
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandpay.java
  Essentials/src/main/resources/messages.properties
Labels: type: enhancement

#3629 Add auto armor equip for kits
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/Kit.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/java/com/earth2me/essentials/utils/EnumUtil.java
  Essentials/src/main/java/com/earth2me/essentials/utils/MaterialUtil.java
  Essentials/src/main/resources/config.yml
Labels: type: enhancement

#3705 Add option to only count online jailed time
  Essentials/src/main/java/com/earth2me/essentials/EssentialsTimer.java
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/com/earth2me/essentials/UserData.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandtogglejail.java
  Essentials/src/main/java/com/earth2me/essentials/utils/DateUtil.java
  Essentials/src/main/resources/config.yml
Labels: type: enhancement

#3904 Prevent sending usage info when executing alternative commands
  Essentials/src/main/java/com/earth2me/essentials/AlternativeCommandsHandler.java
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
Labels: bug: confirmed

#3900 Properly detect enchantments with improper names
  Essentials/src/main/java/com/earth2me/essentials/Enchantments.java
Labels: type: enhancement

#3899 Add option to disable custom server-full message
  Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/resources/config.yml
Labels: type: enhancement

#3923 Update to 1.16.5
  Essentials/src/main/java/com/earth2me/essentials/utils/VersionUtil.java
  README.md
  build.gradle
  providers/PaperProvider/build.gradle
Labels: type: enhancement

#3918 Add slash command support
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/IEssentials.java
  Essentials/src/main/java/com/earth2me/essentials/PlayerList.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandlist.java
  Essentials/src/main/java/com/earth2me/essentials/commands/EssentialsCommand.java
  Essentials/src/main/resources/messages.properties
  EssentialsDiscord/src/main/java/net/essentialsx/discord/DiscordSettings.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/EssentialsDiscord.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/EssentialsJDA.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/interactions/InteractionController.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/interactions/command/InteractionCommand.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/interactions/command/InteractionCommandArgument.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/interactions/command/InteractionCommandArgumentType.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/interactions/command/InteractionEvent.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/interactions/commands/ExecuteCommand.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/interactions/commands/ListCommand.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/interactions/commands/MessageCommand.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/listeners/DiscordCommandDispatcher.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/util/DiscordCommandSender.java
  EssentialsDiscord/src/main/java/net/essentialsx/discord/util/DiscordUtil.java
  EssentialsDiscord/src/main/resources/config.yml
Labels: type: enhancement

#3928 Fix bPermissions not showing up as unsupported
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandessentials.java
Labels: type: bugfix

#3905 Fix various problems with firework meta (de)serialization
  Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java
  Essentials/src/main/java/com/earth2me/essentials/items/AbstractItemDb.java
  Essentials/src/main/java/com/earth2me/essentials/utils/MaterialUtil.java
Labels: type: bugfix, type: enhancement

#3812 Improve VersionUtil version checks
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandessentials.java
  Essentials/src/main/java/com/earth2me/essentials/utils/VersionUtil.java
  Essentials/src/main/resources/messages.properties
  providers/NMSReflectionProvider/src/main/java/net/ess3/nms/refl/ReflUtil.java
Labels: type: enhancement

#3917 Fix invalid formatted jail time strings in whois/seen
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/IUser.java
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandseen.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandwhois.java
Labels: type: bugfix
