Repository EssentialsX/Essentials, pull requests merged in 2021-02, with the labels that each got.

#3694 Add support for material tags in enchant signs
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/IEssentials.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignEnchant.java
  providers/BaseProviders/src/main/java/net/ess3/provider/MaterialTagProvider.java
  providers/BaseProviders/src/main/java/net/ess3/provider/providers/BukkitMaterialTagProvider.java
  providers/PaperProvider/src/main/java/net/ess3/provider/providers/PaperMaterialTagProvider.java
Labels: type: enhancement

#3910 Add config option to disable message social spy
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/java/com/earth2me/essentials/messaging/SimpleMessageRecipient.java
  Essentials/src/main/resources/config.yml
Labels: type: enhancement

#3909 Add /kitreset command
  Essentials/src/main/java/com/earth2me/essentials/Kit.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandkitreset.java
  Essentials/src/main/resources/messages.properties
  Essentials/src/main/resources/plugin.yml
Labels: type: enhancement

#3911 Infer jail name when the server only has one jail configured
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandtogglejail.java
Labels: type: enhancement

#3914 Fix AntiBuild performing place checks for block state changes
  EssentialsAntiBuild/src/main/java/com/earth2me/essentials/antibuild/EssentialsAntiBuildListener.java
Labels: type: bugfix

#3938 Add API packages
  Essentials/src/main/java/net/essentialsx/api/v2/package-info.java
  Essentials/src/main/java/net/essentialsx/api/v2/services/package-info.java
  Essentials/src/test/java/com/earth2me/essentials/FakeServer.java
Labels: type: api

#3907 Show custom item aliases in /itemdb
  Essentials/src/main/java/com/earth2me/essentials/commands/Commanditemdb.java
  Essentials/src/main/java/com/earth2me/essentials/items/CustomItemResolver.java
Labels: type: enhancement

#3912 Add world aliases for Chat
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/resources/config.yml
  EssentialsChat/src/main/java/com/earth2me/essentials/chat/EssentialsChatPlayerListenerLowest.java
Labels: type: enhancement

#3969 Improve logging of dangerous userdata edge cases
  Essentials/src/main/java/com/earth2me/essentials/UserMap.java
  Essentials/src/main/java/com/earth2me/essentials/api/Economy.java
Labels: type: enhancement

#3985 Update FakeWorld
  Essentials/src/main/java/com/earth2me/essentials/craftbukkit/FakeWorld.java
Labels: type: enhancement

#3702 Add Baltop API
  Essentials/src/main/java/com/earth2me/essentials/BalanceTopImpl.java
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/IEssentials.java
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/com/earth2me/essentials/UserData.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandbalancetop.java
  Essentials/src/main/java/net/essentialsx/api/v2/services/BalanceTop.java
Labels: type: api, type: enhancement

#3941 Fix further incorrect messages for jail countdowns
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandtogglejail.java
Labels: type: bugfix

#3946 Allow blank currency symbols
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
Labels: type: bugfix

#3989 Add /editsign copy + paste
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandeditsign.java
  Essentials/src/main/resources/messages.properties
  Essentials/src/main/resources/plugin.yml
Labels: type: enhancement

#3961 Add new signs for recently added virtual commands
  Essentials/src/main/java/com/earth2me/essentials/signs/SignAnvil.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignCartography.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignGrindstone.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignLoom.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignSmithing.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignWorkbench.java
  Essentials/src/main/java/com/earth2me/essentials/signs/Signs.java
  Essentials/src/main/resources/config.yml
Labels: type: enhancement

#3744 Add support for commands.yml aliases in command cooldowns
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/main/java/com/earth2me/essentials/IEssentials.java
  providers/BaseProviders/src/main/java/net/ess3/provider/FormattedCommandAliasProvider.java
  providers/NMSReflectionProvider/src/main/java/net/ess3/nms/refl/providers/ReflFormattedCommandAliasProvider.java
Labels: type: bugfix

#4000 Fix invalid configuration section for world aliases
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
Labels: type: bugfix

#3915 Fix afk message being sent when event cancelled
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandafk.java
Labels: type: bugfix

#3906 Show UUIDs in /seen
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandseen.java
Labels: type: enhancement

#3964 Add permission to adjust delay in /spawner command
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandspawner.java
Labels: type: enhancement

#4002 Document XMPP config and require server TLS by default
  EssentialsXMPP/src/main/java/com/earth2me/essentials/xmpp/XMPPManager.java
  EssentialsXMPP/src/main/resources/config.yml
Labels: type: enhancement

#4016 Fix some futures in AsyncTeleport never completing
  Essentials/src/main/java/com/earth2me/essentials/AsyncTeleport.java
Labels: type: bugfix
