Repository EssentialsX/Essentials, pull requests merged in 2021-05, with the labels that each got.

#4083 [CI-SKIP] Automatically publish 2.x javadocs
  .github/workflows/build-master.yml
  .github/workflows/build-pr.yml
Labels: type: enhancement

#4130 Fix kit-auto-equip not working on versions < 1.14
  Essentials/src/main/java/com/earth2me/essentials/Kit.java
Labels: type: bugfix

#4128 Prevent stack overflow when finding an EssX cmd as alternative
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
Labels: type: bugfix

#4131 Add way for time and weather signs to display the time/weather
  Essentials/src/main/java/com/earth2me/essentials/signs/SignTime.java
  Essentials/src/main/java/com/earth2me/essentials/signs/SignWeather.java
  Essentials/src/main/resources/messages.properties
Labels: type: enhancement

#4095 Unformat item lore and name when serializing items
  Essentials/src/main/java/com/earth2me/essentials/items/AbstractItemDb.java
  Essentials/src/main/java/com/earth2me/essentials/utils/FormatUtil.java
Labels: type: bugfix

#4141 Fix netlify deploy message
  .github/workflows/build-master.yml
Labels: type: bugfix

#3975 Migrate to new Vault provider and economy integration
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/EssentialsPluginListener.java
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/com/earth2me/essentials/UserMap.java
  Essentials/src/main/java/com/earth2me/essentials/api/Economy.java
  Essentials/src/main/java/com/earth2me/essentials/economy/EconomyLayer.java
  Essentials/src/main/java/com/earth2me/essentials/economy/EconomyLayers.java
  Essentials/src/main/java/com/earth2me/essentials/economy/layers/VaultLayer.java
  Essentials/src/main/java/com/earth2me/essentials/economy/vault/VaultEconomyProvider.java
  Essentials/src/main/java/com/earth2me/essentials/metrics/MetricsWrapper.java
  Essentials/src/main/java/com/earth2me/essentials/register/payment/Method.java
  Essentials/src/main/java/com/earth2me/essentials/register/payment/Methods.java
  Essentials/src/main/java/com/earth2me/essentials/register/payment/methods/VaultEco.java
  Essentials/src/test/java/com/earth2me/essentials/EconomyTest.java
  Essentials/src/test/java/com/earth2me/essentials/FakeServer.java
Labels: type: enhancement

#4147 Fix vault provider account creation
  Essentials/src/main/java/com/earth2me/essentials/UserMap.java
  Essentials/src/main/java/com/earth2me/essentials/economy/vault/VaultEconomyProvider.java
Labels: type: bugfix

#4149 Ensure NPC userdata creation for Citizen NPCs
  Essentials/src/main/java/com/earth2me/essentials/economy/vault/VaultEconomyProvider.java
Labels: type: bugfix

#4150 Fix a minor issue with support status detection
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandessentials.java
  Essentials/src/main/java/com/earth2me/essentials/utils/VersionUtil.java
Labels: type: bugfix

#4151 Fix ClassNotFoundException when vault is missing
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
Labels: type: bugfix

#4148 Update Gradle to 7.0.2; misc build improvements
  .github/workflows/build-master.yml
  .github/workflows/build-pr.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: type: enhancement

#4166 Fix minor issue with server support minor issue fix
  Essentials/src/main/java/com/earth2me/essentials/utils/VersionUtil.java
Labels: bug: confirmed, type: bugfix

#4168 Set Gradle toolchain to JDK 16
  build.gradle
Labels: type: enhancement

#4169 Add {PREFIX} and {SUFFIX} to custom join/quit messages
  Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java
  Essentials/src/main/resources/config.yml
Labels: type: enhancement

#4177 Add support for dev/rc/beta/alpha build types
  Essentials/src/main/java/com/earth2me/essentials/updatecheck/UpdateChecker.java
Labels: type: enhancement

#4143 Add ItemStack 1.8.8+ cross-version PersistentDataContainer
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/IEssentials.java
  providers/BaseProviders/src/main/java/net/ess3/provider/PersistentDataProvider.java
  providers/BaseProviders/src/main/java/net/ess3/provider/providers/ModernPersistentDataProvider.java
  providers/NMSReflectionProvider/src/main/java/net/ess3/nms/refl/providers/ReflPersistentDataProvider.java
Labels: type: enhancement

#4133 Add prevent-type permissions for /itemname
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandhat.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commanditemname.java
  Essentials/src/main/java/com/earth2me/essentials/perm/IPermissionsHandler.java
  Essentials/src/main/java/com/earth2me/essentials/perm/PermissionsHandler.java
  Essentials/src/main/java/com/earth2me/essentials/perm/impl/ConfigPermissionsHandler.java
  Essentials/src/main/java/com/earth2me/essentials/perm/impl/SuperpermsHandler.java
  Essentials/src/main/java/com/earth2me/essentials/utils/TriState.java
Labels: type: enhancement

#4048 Add book page serialization
  Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java
  Essentials/src/main/java/com/earth2me/essentials/items/AbstractItemDb.java
  Essentials/src/main/java/com/earth2me/essentials/utils/MaterialUtil.java
Labels: type: enhancement, type: problem

#3963 Only use convert spawners tagged by the give command
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/EssentialsBlockListener.java
  Essentials/src/main/java/com/earth2me/essentials/items/FlatItemDb.java
  Essentials/src/main/java/com/earth2me/essentials/items/LegacyItemDb.java
  providers/NMSReflectionProvider/src/main/java/net/ess3/nms/refl/providers/ReflServerStateProvider.java
Labels: type: bugfix

#4178 Check legacy "NPC:" UUIDs in VaultEconomyProvider#hasAccount
  Essentials/src/main/java/com/earth2me/essentials/economy/vault/VaultEconomyProvider.java
Labels: bug: confirmed
