Repository EssentialsX/Essentials, pull requests merged in 2021-06, with the labels that each got.

#4188 Fix various NPC account lookup issues
  Essentials/src/main/java/com/earth2me/essentials/EssentialsUserConf.java
  Essentials/src/main/java/com/earth2me/essentials/UserData.java
  Essentials/src/main/java/com/earth2me/essentials/UserMap.java
  Essentials/src/main/java/com/earth2me/essentials/api/Economy.java
  Essentials/src/test/java/com/earth2me/essentials/FakeServer.java
Labels: type: bugfix

#4199 Fix offline player account creation
  Essentials/src/main/java/com/earth2me/essentials/UserMap.java
  Essentials/src/main/java/com/earth2me/essentials/economy/vault/VaultEconomyProvider.java
Labels: bug: confirmed

#4200 Add option to ignore vanished players from sleeping
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/resources/config.yml
Labels: type: enhancement

#4201 Fix sleeping ignored vanish setting overriding permission
  Essentials/src/main/java/com/earth2me/essentials/User.java
Labels: bug: confirmed

#4202 Clean up gradle build scripts
  .gitignore
  Essentials/build.gradle
  EssentialsAntiBuild/build.gradle
  EssentialsChat/build.gradle
  EssentialsGeoIP/build.gradle
  EssentialsProtect/build.gradle
  EssentialsSpawn/build.gradle
  EssentialsXMPP/build.gradle
  build-logic/build.gradle.kts
  build-logic/src/main/groovy/GitUtil.groovy
  build-logic/src/main/kotlin/EssentialsModuleExtension.kt
  build-logic/src/main/kotlin/FileCopyTask.kt
  build-logic/src/main/kotlin/constants.kt
  build-logic/src/main/kotlin/essentials.base-conventions.gradle.kts
  build-logic/src/main/kotlin/essentials.module-conventions.gradle.kts
  build-logic/src/main/kotlin/essentials.parent-build-logic.gradle.kts
  build-logic/src/main/kotlin/essentials.shadow-module.gradle.kts
  build.gradle
  providers/1_8Provider/build.gradle
  providers/BaseProviders/build.gradle
  providers/NMSReflectionProvider/build.gradle
  providers/PaperProvider/build.gradle
  settings.gradle
  settings.gradle.kts
Labels: type: enhancement

#4072 Migrate to Configurate
  Essentials/build.gradle
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/EssentialsUpgrade.java
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/IUser.java
  Essentials/src/main/java/com/earth2me/essentials/Jails.java
  Essentials/src/main/java/com/earth2me/essentials/Kits.java
  Essentials/src/main/java/com/earth2me/essentials/RandomTeleport.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/java/com/earth2me/essentials/UserData.java
  Essentials/src/main/java/com/earth2me/essentials/Warps.java
  Essentials/src/main/java/com/earth2me/essentials/Worth.java
  Essentials/src/main/java/com/earth2me/essentials/api/Economy.java
  Essentials/src/main/java/com/earth2me/essentials/api/IJails.java
  Essentials/src/main/java/com/earth2me/essentials/api/IReload.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandcreatekit.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commanddelkit.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandkit.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandkitreset.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandshowkit.java
  Essentials/src/main/java/com/earth2me/essentials/config/ConfigurateUtil.java
  Essentials/src/main/java/com/earth2me/essentials/config/ConfigurationSaveTask.java
  Essentials/src/main/java/com/earth2me/essentials/config/EssentialsConfiguration.java
  Essentials/src/main/java/com/earth2me/essentials/config/EssentialsUserConfiguration.java
  Essentials/src/main/java/com/earth2me/essentials/config/annotations/DeleteOnEmpty.java
  Essentials/src/main/java/com/earth2me/essentials/config/entities/CommandCooldown.java
  Essentials/src/main/java/com/earth2me/essentials/config/holders/UserConfigHolder.java
  Essentials/src/main/java/com/earth2me/essentials/config/processors/DeleteOnEmptyProcessor.java
  Essentials/src/main/java/com/earth2me/essentials/config/serializers/BigDecimalTypeSerializer.java
  Essentials/src/main/java/com/earth2me/essentials/config/serializers/LocationTypeSerializer.java
  Essentials/src/main/java/com/earth2me/essentials/config/serializers/MaterialTypeSerializer.java
  Essentials/src/main/java/com/earth2me/essentials/economy/vault/VaultEconomyProvider.java
  Essentials/src/main/java/com/earth2me/essentials/items/CustomItemResolver.java
  Essentials/src/main/java/com/earth2me/essentials/settings/Jails.java
  Essentials/src/main/java/com/earth2me/essentials/settings/Spawns.java
  Essentials/src/main/java/com/earth2me/essentials/storage/AbstractDelayedYamlFileReader.java
  Essentials/src/main/java/com/earth2me/essentials/storage/AbstractDelayedYamlFileWriter.java
  Essentials/src/main/java/com/earth2me/essentials/storage/AsyncStorageObjectHolder.java
  Essentials/src/main/java/com/earth2me/essentials/storage/BukkitConstructor.java
  Essentials/src/main/java/com/earth2me/essentials/storage/Comment.java
  Essentials/src/main/java/com/earth2me/essentials/storage/EnchantmentLevel.java
  Essentials/src/main/java/com/earth2me/essentials/storage/IStorageObjectHolder.java
  Essentials/src/main/java/com/earth2me/essentials/storage/IStorageReader.java
  Essentials/src/main/java/com/earth2me/essentials/storage/IStorageWriter.java
  Essentials/src/main/java/com/earth2me/essentials/storage/ListType.java
  Essentials/src/main/java/com/earth2me/essentials/storage/MapKeyType.java
  Essentials/src/main/java/com/earth2me/essentials/storage/MapValueType.java
  Essentials/src/main/java/com/earth2me/essentials/storage/ObjectLoadException.java
  Essentials/src/main/java/com/earth2me/essentials/storage/StorageObject.java
  Essentials/src/main/java/com/earth2me/essentials/storage/YamlStorageReader.java
  Essentials/src/main/java/com/earth2me/essentials/storage/YamlStorageWriter.java
  Essentials/src/main/java/net/ess3/api/IReload.java
  EssentialsGeoIP/src/main/java/com/earth2me/essentials/geoip/EssentialsGeoIPPlayerListener.java
  EssentialsSpawn/src/main/java/com/earth2me/essentials/spawn/SpawnStorage.java
  EssentialsXMPP/src/main/java/com/earth2me/essentials/xmpp/UserManager.java
  EssentialsXMPP/src/main/java/com/earth2me/essentials/xmpp/XMPPManager.java
  build-logic/src/main/kotlin/essentials.base-conventions.gradle.kts
Labels: type: enhancement

#4203 Lazy load locations in Configurate
  Essentials/src/main/java/com/earth2me/essentials/UserData.java
  Essentials/src/main/java/com/earth2me/essentials/config/EssentialsConfiguration.java
  Essentials/src/main/java/com/earth2me/essentials/config/entities/LazyLocation.java
  Essentials/src/main/java/com/earth2me/essentials/config/holders/UserConfigHolder.java
  Essentials/src/main/java/com/earth2me/essentials/config/serializers/LocationTypeSerializer.java
  Essentials/src/test/java/com/earth2me/essentials/EconomyTest.java
  Essentials/src/test/java/com/earth2me/essentials/FakeServer.java
  Essentials/src/test/java/com/earth2me/essentials/MessagingTest.java
  Essentials/src/test/java/com/earth2me/essentials/StorageTest.java
  Essentials/src/test/java/com/earth2me/essentials/ToggleTest.java
  Essentials/src/test/java/com/earth2me/essentials/UserTest.java
  Essentials/src/test/java/com/earth2me/essentials/UtilTest.java
  providers/1_8Provider/src/main/java/com/earth2me/essentials/FakeWorld.java
Labels: type: bugfix

#4206 Fix remaining uses of Location over LazyLocation
  Essentials/src/main/java/com/earth2me/essentials/RandomTeleport.java
  Essentials/src/main/java/com/earth2me/essentials/Warps.java
  Essentials/src/main/java/com/earth2me/essentials/config/EssentialsConfiguration.java
  EssentialsSpawn/src/main/java/com/earth2me/essentials/spawn/Commandspawn.java
  EssentialsSpawn/src/main/java/com/earth2me/essentials/spawn/EssentialsSpawnPlayerListener.java
  EssentialsSpawn/src/main/java/com/earth2me/essentials/spawn/SpawnStorage.java
Labels: type: bugfix

#4208 Fix setting of locations to LazyLocations + Shade CheckerQual
  Essentials/build.gradle
  Essentials/src/main/java/com/earth2me/essentials/config/EssentialsConfiguration.java
Labels: type: bugfix

#4210 Fix invalid CommandCooldowns causing NPEs
  Essentials/src/main/java/com/earth2me/essentials/config/EssentialsConfiguration.java
  Essentials/src/main/java/com/earth2me/essentials/config/annotations/DeleteIfIncomplete.java
  Essentials/src/main/java/com/earth2me/essentials/config/entities/CommandCooldown.java
  Essentials/src/main/java/com/earth2me/essentials/config/holders/UserConfigHolder.java
  Essentials/src/main/java/com/earth2me/essentials/config/processors/DeleteIfIncompleteProcessor.java
Labels: type: bugfix

#4212 Fix parsing of command cooldowns with invalid data
  Essentials/src/main/java/com/earth2me/essentials/config/EssentialsConfiguration.java
  Essentials/src/main/java/com/earth2me/essentials/config/entities/CommandCooldown.java
  Essentials/src/main/java/com/earth2me/essentials/config/serializers/CommandCooldownSerializer.java
Labels: type: bugfix

#4214 Fix empty paths with Configurate
  Essentials/src/main/java/com/earth2me/essentials/Warps.java
  Essentials/src/main/java/com/earth2me/essentials/config/EssentialsConfiguration.java
Labels: type: bugfix

#4132 Add config option to respawn jailed players to spawn
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/java/com/earth2me/essentials/User.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandtogglejail.java
  Essentials/src/main/resources/config.yml
Labels: type: enhancement

#4216 Prevent getting jail worlds before world load
  Essentials/src/main/java/com/earth2me/essentials/Jails.java
  Essentials/src/main/resources/messages.properties
Labels: type: bugfix

#4217 Fix EssentialsSpawn not defaulting on default group
  EssentialsSpawn/src/main/java/com/earth2me/essentials/spawn/SpawnStorage.java
Labels: type: bugfix

#4218 Fix invalid mail key
  Essentials/src/main/java/com/earth2me/essentials/UserData.java
  Essentials/src/main/java/com/earth2me/essentials/config/holders/UserConfigHolder.java
Labels: type: bugfix

#4219 Fix broken cooldowns causing exceptions
  Essentials/src/main/java/com/earth2me/essentials/UserData.java
Labels: type: bugfix

#4180 Fix /book command not supporting multi-word title & author
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandbook.java
Labels: type: enhancement

#3874 Fix damage from exploding beds being cancelled
  EssentialsProtect/src/main/java/com/earth2me/essentials/protect/EssentialsProtectEntityListener.java
Labels: type: bugfix

#3882 Allow enchants on fireworks/charges/potions/banners
  Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java
Labels: type: bugfix

#4226 Allow /balancetop to hide players with a balance of 0
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandbalancetop.java
  Essentials/src/main/resources/config.yml
Labels: type: enhancement

#4230 Fix NPE for list group
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
Labels: bug: confirmed

#4234 Fix NPE in UserData#getHome
  Essentials/src/main/java/com/earth2me/essentials/UserData.java
Labels: type: bugfix

#4237 Fix invalid empty value for BigDecimal
  Essentials/src/main/java/com/earth2me/essentials/config/serializers/BigDecimalTypeSerializer.java
Labels: type: bugfix

#4240 Fix invalid home locations giving blank errors
  Essentials/src/main/java/com/earth2me/essentials/UserData.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandhome.java
Labels: module: main, type: bugfix

#4244 Implement home cleanup utility
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandessentials.java
  Essentials/src/main/resources/messages.properties
Labels: module: main, type: enhancement

#4249 Don't add incomplete cooldowns
  Essentials/src/main/java/com/earth2me/essentials/UserData.java
Labels: module: main, type: bugfix

#3248 Add serialization support to kits
  Essentials/src/main/java/com/earth2me/essentials/Essentials.java
  Essentials/src/main/java/com/earth2me/essentials/IEssentials.java
  Essentials/src/main/java/com/earth2me/essentials/ISettings.java
  Essentials/src/main/java/com/earth2me/essentials/Kit.java
  Essentials/src/main/java/com/earth2me/essentials/Settings.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandcreatekit.java
  Essentials/src/main/resources/config.yml
  Essentials/src/main/resources/messages.properties
  providers/BaseProviders/src/main/java/net/ess3/provider/SerializationProvider.java
  providers/PaperProvider/src/main/java/net/ess3/provider/providers/PaperSerializationProvider.java
Labels: module: main, type: enhancement

#4276 Prevent NPEs in /powertool
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandpowertool.java
Labels: module: main, type: bugfix

#4273 Fix pickup delay with essentials.build.pickup permission
  EssentialsAntiBuild/src/main/java/com/earth2me/essentials/antibuild/EssentialsAntiBuildListener.java
Labels: module: antibuild, type: bugfix

#4279 Fix missing translation param in ice command
  Essentials/src/main/java/com/earth2me/essentials/commands/Commandice.java
Labels: module: main, type: bugfix

#4280 Improve itemlore and itemname tab completion
  Essentials/src/main/java/com/earth2me/essentials/Kit.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commanditemlore.java
  Essentials/src/main/java/com/earth2me/essentials/commands/Commanditemname.java
  Essentials/src/main/java/com/earth2me/essentials/utils/MaterialUtil.java
  Essentials/src/main/resources/messages.properties
Labels: module: main, type: enhancement
